### ISSUE TITLE
Donating Books

### ISSUE THREAD

**Issue by vaibhavmule** [Mindgreppers/thevillagelab#1]
I have read [wiki](https://github.com/Mindgreppers/thevillagelab/wiki) and found out that there is need of books.

I would like to buy books worth of Rs1000 and donate to [thevillagelab](https://github.com/Mindgreppers/thevillagelab/)

If you wanna consider this, please reply back with list books to order with amazon links.

Thanks.

**Comment by sucheta92** [comment]
Thank you so much for the contribution! 

Here is a list of books that you might want to consider: 

Riddles in your teacup: http://www.amazon.in/Riddles-Your-Teacup-Partha-Ghose-ebook/dp/B015A9XAOI/ref=sr_1_1?ie=UTF8&qid=1455122010&sr=8-1&keywords=riddles+in+your+teacup

Totto Chan: http://www.amazon.in/gp/product/8123717601?psc=1&redirect=true&ref_=ox_sc_act_title_2&smid=A24UOU64O12TNC

Fun with leaves: http://www.amazon.in/gp/product/9351031373?psc=1&redirect=true&ref_=ox_sc_act_title_3&smid=A1TSQTFRN94P4R

Vigyan ke Kamal: http://www.amazon.in/gp/product/8184778589?psc=1&redirect=true&ref_=ox_sc_act_title_4&smid=A1TSQTFRN94P4R

**Comment by vaibhavmule** [comment]
@sucheta92 Please add more books so that I do not have to pay for delivery charges and that money saved for to buy books.

**Comment by sucheta92** [comment]
Good idea. More books: 

Toys from Trash: http://www.amazon.in/Toys-Trash-Arvind-Gupta%C2%A0/dp/9351030059/ref=sr_1_1?ie=UTF8&qid=1455079516&sr=8-1&keywords=Arvind+Gupta+books

Quick Activities: Science and Craft: http://www.amazon.in/Quick-Activities-Science-Arvind-Gupta/dp/8184772912/ref=sr_1_19?ie=UTF8&qid=1455124053&sr=8-19&keywords=Arvind+Gupta+books

Art With Your Thumbs (Thumbprints): http://www.amazon.in/Your-Thumbs-Thumbprints-Arvind-Gupta/dp/8184770448/ref=sr_1_5?ie=UTF8&qid=1455124120&sr=8-5&keywords=Arvind+Gupta+books

Story of the Solar Energy: http://www.amazon.in/Story-Solar-Energy-Arvind-Gupta/dp/8184778287/ref=sr_1_6?ie=UTF8&qid=1455124120&sr=8-6&keywords=Arvind+Gupta+books

How Children Learn: http://www.amazon.in/Children-Learn-Classics-Child-Development/dp/0201484048/ref=sr_1_1?ie=UTF8&qid=1455127037&sr=8-1&keywords=john+holt AND/OR How Children Fail: http://www.amazon.in/How-Children-Fail-John-Holt/dp/0140135561/ref=sr_1_2_twi_har_2_twi_pap_2?ie=UTF8&qid=1455127037&sr=8-2&keywords=john+holt (depending on which one your budget permits)

**Comment by vaibhavmule** [comment]
Ordered!

This is list of books I have ordered!

- Toys From Trash, Arvind Gupta 
- The Story of Solar Energy, Arvind Gupta
- Fun with Leaves, Arvind Gupta
- How Children Learn (Classics in Child Development), Holt, John

All of these hopefully will arrive at Ghomakad.

Thanks.

**Comment by mastersilv3r** [comment]
That's very nice of you Vaibhav. Thanks!

**Comment by sucheta92** [comment]
So nice of you, Vaibhav! Much much appreciated :)
